version: "3.7"

services:
  redis:
    build: redis
    restart: always
    networks:
      - app-network
    ports:
      - "6379:6379"

  sender:
    build: sender
    restart: always
    env_file:
      - config.env
    networks:
      - app-network
    depends_on:
      - redis



networks:
    app-network: